name: Release

on:
    push:
        tags:
          - 'v*'

jobs:
    release:
        runs-on: macos-latest
        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

        